### ISSUE TITLE
react找不到GuacaPlayer怎么办？

### ISSUE THREAD

**Issue by fengnex** [goodwinfame/react-guacamole-player#2]
import GuacaPlayer from 'GuacaPlayer'

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
 ERROR  Failed to compile with 1 errors

This dependency was not found:

* GuacaPlayer in ./src/pages/**/Test.tsx

To install it, you can run: npm install --save GuacaPlayer

**Comment by fengnex** [comment]
node_modules\react-guacamole-player
这下面的内容看起来都安装好了，yarn add react-guacamole-player用这个安装的

**Comment by goodwinfame** [comment]
> node_modules\react-guacamole-player
> 这下面的内容看起来都安装好了，yarn add react-guacamole-player用这个安装的

import GuacaPlayer from 'react-guacamole-player'
这样引入，文档描述不正确，需要更新

**Comment by fengnex** [comment]
请问这个player是干嘛的
是Apache guacamole的客户端吗？

**Comment by goodwinfame** [comment]
> 请问这个player是干嘛的
> 是Apache guacamole的客户端吗？

用于播放Apache guacamole的session文件，也就是录屏文件。
